version: '3.9'
services:
  db:
    image: postgres
    shm_size: 128mb
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_DB: fiap
      POSTGRES_PASSWORD: fiap
    ports:
      - "3310:5432"
    expose:
      - "5432"
    networks:
      - trips-postgres-network
networks:
  trips-postgres-network:
    driver: bridge
